# Generated by Django 5.2.3 on 2025-06-12 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("INSERT INTO auth_group (id, name) VALUES (1, 'Доктор'), (2, 'Администратор'), (3, 'Пациент')")
    ]
