# Generated by Django 5.2.3 on 2025-06-13 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_consultation_clinic_alter_consultation_doctor_and_more'),
        ('users', '0002_add_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='clinics',
            field=models.ManyToManyField(blank=True, null=True, related_name='doctors', to='clinics.clinic', verbose_name='Clinics'),
        ),
        migrations.AlterField(
            model_name='user',
            name='specializations',
            field=models.ManyToManyField(blank=True, null=True, related_name='doctors', to='clinics.specialization', verbose_name='Specializations'),
        ),
    ]
